plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	runtimeOnly 'com.mysql:mysql-connector-j'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'com.github.ben-manes.caffeine:caffeine'

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation('org.springframework.boot:spring-boot-starter-web') {
    	exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
	}

	implementation 'org.springframework.boot:spring-boot-starter-undertow'
	implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.retry:spring-retry'
	implementation 'org.springframework:spring-aspects'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	implementation 'org.springframework.kafka:spring-kafka'

	implementation(platform("software.amazon.awssdk:bom:2.27.21"))

	// TODO: implement S3 with Spring Cloud AWS starter also
	implementation("software.amazon.awssdk:s3")
	implementation("software.amazon.awssdk:sqs")
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs:3.1.1'
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-sns:3.1.1'
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-dynamodb:3.1.1'
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-parameter-store:3.1.1'

	implementation 'org.springframework.ai:spring-ai-starter-model-ollama:1.1.2'

	implementation 'org.liquibase:liquibase-core'
	runtimeOnly 'org.postgresql:postgresql'
	compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}


tasks.named('test') {
	useJUnitPlatform()
}

jar {
	archiveBaseName.set('angula')
	archiveVersion.set('api')
}