#--> Application
spring.application.name=angula

#--> Server
server.port=8085
server.address=localhost

#--> PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/angula
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#--> database / DataJpa / Hibernate
spring.jpa.show-sql=false
spring.jta.enabled=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

#--> liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

#--> Logger
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.structured.format.console=com.example.angula.config.CustomLogger
logging.level.org.hibernate=ERROR

#--> Actuator
management.endpoints.web.exposure.include=*

#--> Devtools
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

#--> Profiles
spring.profiles.active=dev

#--> Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.cache-names=client,task

#--> Custom Properies
ready.message="Let's Do It !!!"
reactor.service=false
reactor.sweet=yes
reactor.scheduler.log=false
reactor.scheduler.yt=false
reactor.scheduler.dynamic=false

#--> YT Playlist Config
yt.playlist.key=${YT_PLAYLIST_KEY}
yt.key=${YT_KEY}
yt.baseurl=https://www.googleapis.com/youtube/v3
yt.part=snippet
yt.maxResults=50

#--> SheetDB
sheet.url=${SHEET_DB_KEY}

#--> Spring Security
spring.security.user.name=alok
spring.security.user.password=1234
spring.security.user.roles=USER,ADMIN

#--> AWS Configs
cloud.aws.creds.access-key=${IAM_ACCESS_KEY}
cloud.aws.creds.secret-key=${IAM_SECRET_KEY}
cloud.aws.s3.bucket.name=${S3_BUCKET_NAME}