#--> Conditional Properties
ready.message="Develop it !!!"
reactor.service=true
angula.dynamic.controller=${DYNAMIC_CONTROLLER}

#--> Logging
# levels = trace < debug < info < warn < error < fatal
logging.level.root=info
logging.level.org.springframework.security=debug

#--> MySql Database
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#--> Spring Ai Ollama Config
spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL}

#--> AWS Configs
cloud.aws.creds.access-key=${IAM_ACCESS_KEY}
cloud.aws.creds.secret-key=${IAM_SECRET_KEY}
cloud.aws.s3.bucket.name=${S3_BUCKET_NAME}
cloud.aws.sqs.url=${SQS_URL}
cloud.aws.sqs.name=${SQS_NAME}
cloud.aws.sns.topic.email.arn=${SNS_TOPIC_EMAIL_ARN}
spring.config.import=${PARAMETER_STORE}

# --> AWS Credentials Configs
spring.cloud.aws.credentials.access-key=${IAM_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${IAM_SECRET_KEY}
spring.cloud.aws.region.static=${AWS_REGION}

# --> Apache Kafka Configs
spring.kafka.bootstrap-servers=${AIVEN_KAFKA_URI}
spring.kafka.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${AIVEN_KAFKA_USER}" password="${AIVEN_KAFKA_PASSWORD}"
# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Consumer Config
spring.kafka.consumer.group-id=${AIVEN_KAFKA_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer