#--> Application
spring.application.name=angula

#--> database / DataJpa / Hibernate
spring.datasource.url=jdbc:postgresql://localhost:5432/angula
spring.datasource.username=postgres
spring.datasource.password=aksql
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.show-sql=true
spring.jta.enabled=false
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.open-in-view=false

#--> liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

#--> Logger
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.structured.format.console=com.example.angula.config.CustomLogger
logging.level.org.hibernate=ERROR

#--> Actuator
management.endpoints.web.exposure.include=*

#--> Devtools
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

#--> Profiles
spring.profiles.active=dev

#--> Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.cache-names=client,task

#--> Custom Properies
ready.message="Let's Do It !!!"
reactor.service = false
reactor.sweet = yes
reactor.scheduler.log = false
reactor.scheduler.yt = false
reactor.scheduler.dynamic = false

#--> YT Playlist Config
yt.playlist.key = PL-bgVzzRdaPhNeXyQBtp8hMlUc14J2kRK
yt.key= AIzaSyAfsjPppNR3vKNqzX_ZiYqbnJYc8XE0E2o
yt.baseurl = https://www.googleapis.com/youtube/v3
yt.part = snippet
yt.maxResults = 50

#--> Jackson
spring.jackson.serialization.write-dates-as-timestamps: false

#--> Spring Security
spring.security.user.name = alokg252
spring.security.user.password = pass@123
spring.security.user.roles = USER,ADMIN

