# Gson
spring.mvc.converters.preferred-json-mapper=gson

# Conditional Properties
ready.message="Develop it !!!"
reactor.service = true

# Logging
# levels = trace < debug < info < warn < error < fatal
# logging.level.root=warn