#--> Gson
spring.mvc.converters.preferred-json-mapper=gson

#--> Conditional Properties
ready.message="Develop it !!!"
reactor.service=true
angula.dynamic.controller=${DYNAMIC_CONTROLLER}

#--> Logging
# levels = trace < debug < info < warn < error < fatal
logging.level.root=warn
logging.level.org.springframework.security=debug

#--> MySql Database
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver